version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    labels:
      - "dependabot"
      - "PR-merge"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
